First task is completed
js-tasks-ru/jsbasic-20200903_lex-marck pull request #1
Opened 2020-09-05 11:43 UTC by Slobodad

2020-09-05 11:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Вычислить факториал
- факториал 1 равен 1
- факториал 3 равен 6 
- факториал 5 равен 120 
- факториал 0 равен 1
```
```diff
Первая задача
+ 1+1=2
```
```diff
Проверка на спам
- должна возвращать true для 'free xxxxx'
- должна возвращать false для 'innocent rabbit'
- должна возвращать true для '1XbeT now'
```
```diff
Усечение строки
- должна усекать строку 
- должна не трогать короткую строку 
```
```diff
Допишите функцию валидации имени пользователя
- если содержит пробелы, то false
- если меньше 4 символов то false
- если имя корректное, то true
```
```diff
Сделать первый символ заглавным
- должна работать для строки из одной буквы
- должна работать для пустой строки
- должна делать первый символ заглавным
```

2020-09-14 10:38 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-09-14 11:53 UTC, koalex approved these changes

2020-09-14 11:53 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-09-14 11:55 UTC, koalex commented on 0-module/1-task/index.js
> +sum(2,6);
удали эту строку

2020-09-14 11:55 UTC, koalex requested changes
0-module-1-task удали строку 11

2020-09-14 12:07 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-09-14 13:46 UTC, koalex approved these changes
ok

2020-09-14 13:46 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-09-14 13:49 UTC, koalex requested changes

2020-09-14 13:49 UTC, koalex commented on 1-module/2-task/index.js
> +sayHello();
удали строку 30

2020-09-14 13:54 UTC, koalex approved these changes
сейчас вроде всё ОК

2020-09-14 13:54 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-09-14 13:57 UTC, koalex approved these changes
ещё раз...

2020-09-14 13:58 UTC, merged